### ISSUE TITLE
"no creation date could be found"

### ISSUE THREAD

**Issue by L0cutus** [sawhney17/logseq-datetag-plugin#3]
when i try to use this plugin nothing happens , i see only the message on subject

**Comment by sawhney17** [comment]
Can you make sure you have block time stamps enabled in settings?

**Comment by sawhney17** [comment]
And it only starts tracking creation date after you've turned it on. So past notes won't ahve creation dates.

**Comment by L0cutus** [comment]
> Can you make sure you have block time stamps enabled in settings?

oops no, now enabled!

> And it only starts tracking creation date after you've turned it on. So past notes won't ahve creation dates.

even if i reindex the graph?

**Comment by sawhney17** [comment]
Yeah, logseq only tracks the creation date once the option has been enabled in settings unfortunately.
